name: mmf-hfb
channels:
  - defaults
  - conda-forge
  - ioam
  - bokeh
  - mforbes
dependencies:
  - python=3

  # Core
  - scipy
  - uncertainties

  # Performance
  - ipyparallel
  - numba
  - numexpr
  - Cython
  - pyfftw
  - zope.interface
  
  # Documentation
  - ipython
  - notebook
  - nbstripout
  # - xlrd
  # - xlwt
  # - pandas
  
  # Plotting
  - matplotlib
  - holoviews
  - datashader
  - paramnb

  # Testing
  - pytest-flake8
  - pytest-cov
  - pytest-runner
  - pytest-xdist
  - sympy

  # Profiling
  - snakeviz
  - line_profiler
  - memory_profiler

  - mmf_setup
  #- mmfutils

  - pip 
  - pip:
    - scikits.bvp1lg
    #- mmfutils
    - hg+ssh://hg@bitbucket.org/mforbes/mmfutils-fork@0.4.14
    #- pytimeode
    #- hg+ssh://hg@bitbucket.org/mforbes/pytimeode
    #- hg+ssh://hg@bitbucket.org/mforbes/gpe/
  
