name: _qt
channels:
  - defaults
  - conda-forge
  - ioam
  - bokeh
  - mforbes
dependencies:
  - python=3

  # Core
  - scipy
  - uncertainties

  # Performance
  - ipyparallel
  - numba
  - numexpr
  - Cython
  - pyfftw
  
  # Documentation
  - ipython
  - notebook
  - nbstripout

  # Plotting
  - matplotlib
  - holoviews
  - datashader
  - paramnb

  # Testing
  - pytest-flake8
  - pytest-cov
  - pytest-runner
  - pytest-xdist
  # Profiling
  - snakeviz
  - line_profiler
  - memory_profiler
  # document
  - xlrd
  - xlwt
  - pandas

  - mmf_setup

  - pip 
  - pip:
    - scikits.bvp1lg
    #- mmfutils
    - hg+ssh://hg@bitbucket.org/mforbes/mmfutils-fork@0.4.12
    #- pytimeode
    - hg+ssh://hg@bitbucket.org/mforbes/pytimeode@0.9
    - hg+ssh://hg@bitbucket.org/mforbes/gpe/
  
